CRUD_Com_Procedures/Controllers/AlunoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CRUD_Com_Procedures.Models;

namespace CRUD_Com_Procedures.Controllers
{
    public class AlunoController : Controller
    {
        ValidaCpf validaCPF = new();

        private readonly Contexto _context;

        public AlunoController(Contexto context)
        {
            _context = context;
        }
                
        public IActionResult Index()
        {
            return View(_context.Aluno.FromSqlRaw("EXEC DetalheAlunoIndice").ToList());
        }
                
        public IActionResult Details(int id)
        {            
            var aluno =  _context.Aluno.FromSqlRaw("EXEC DetalheAluno " + id).ToList().FirstOrDefault();
            
            return View(aluno);
        }
        public IActionResult Create()
        {
            return View();
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Aluno aluno)
        {

            var query2 = string.Format("EXEC VerificaCPF '{0}'", aluno.Cpf);

            var aluno1 = _context.Aluno.FromSqlRaw(query2).ToList().FirstOrDefault();

            
            if (ModelState.IsValid & validaCPF.IsCpf(aluno.Cpf) & aluno1 == null)
            {
                var query = string.Format("EXEC AddAluno '{0}', '{1}', '{2}', '{3}', {4}",
                    aluno.Nome, aluno.Cpf, aluno.DataNascimento, aluno.Senha, aluno.IsAdm);

                _context.Aluno.FromSqlRaw(query).ToListAsync();

                TempData["MessagemSucessoAdd"] = "Aluno adicionado com sucesso!!";

                return RedirectToAction(nameof(Index));

            }
            else
            {
                TempData["MessagemErrorCPF"] = "CPF invalido ou já cadastrado!!";
                return RedirectToAction(nameof(Create));
            }                
        }
        public IActionResult Edit(int id)
        {
            var aluno = _context.Aluno.FromSqlRaw("EXEC DetalheAluno " + id)
                .ToList().FirstOrDefault();

            return View(aluno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Aluno aluno)
        {
            ValidaCpf validaCPF = new();

            if (ModelState.IsValid & validaCPF.IsCpf(aluno.Cpf))
            {
                var query = string.Format("EXEC EditarAluno {0}, '{1}', '{2}', '{3}', '{4}', {5}",
                    id, aluno.Nome, aluno.Cpf, aluno.DataNascimento, aluno.Senha, aluno.IsAdm);

                _context.Aluno.FromSqlRaw(query).ToListAsync();

                TempData["MessagemSucessoEdit"] = "Informações editadas com sucesso!!";

                return RedirectToAction(nameof(Index));

            }

            TempData["MessagemErrorEdit"] = "Não foi possível editar, veridfique as informações!!";
            return View(aluno);
        }
                
        public IActionResult Delete(int id)
        {
            var aluno = _context.Aluno.FromSqlRaw("EXEC DetalheAluno " + id)
                 .ToList().FirstOrDefault();

            return View(aluno);
        }
                
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {

            _context.Aluno.FromSqlRaw("EXEC DeleteAluno " + id).ToListAsync();

            _context.SaveChangesAsync();

            TempData["MessagemSucessoDel"] = "Cadastro de aluno removido com sucesso!!";
            return RedirectToAction(nameof(Index));
            
        }  
    }
}

CRUD_Com_Procedures/Controllers/CursoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CRUD_Com_Procedures.Models;


namespace CRUD_Com_Procedures.Controllers
{
    public class CursoController : Controller
    {
        private readonly Contexto _context;

        public CursoController(Contexto context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
              return View(_context.Curso.FromSqlRaw("EXEC DetalheCursoIndice").ToList());
        }
        public IActionResult Details(int id)
        {
            var curso = _context.Curso.FromSqlRaw("EXEC DetalheCurso " + id)
                .ToList().FirstOrDefault();
               
            return View(curso);
        }
                
        public IActionResult Create()
        {
            return View();
        }
                
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Curso curso)
        {
            if (ModelState.IsValid)
            {
                var query = string.Format("EXEC AddCurso '{0}', {1}, '{2}'",
                    curso.NomeCurso, curso.Horas, curso.Descricao);

                _context.Curso.FromSqlRaw(query).ToListAsync();

                TempData["MessagemSucessoCadastro"] = "Cadastro de Curso realizado com sucesso!!";
                return RedirectToAction(nameof(Index));

            }
            return View(curso);
        }  
        public IActionResult Edit(int id)
        {
            return View( _context.Curso.FromSqlRaw("EXEC DetalheCurso " + id)
                .ToList().FirstOrDefault());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Curso curso)
        {
            if (ModelState.IsValid)
            {
                var query = string.Format("EXEC EditarCurso {0}, '{1}', {2}, '{3}'",
                    id, curso.NomeCurso, curso.Horas, curso.Descricao);

                _context.Curso.FromSqlRaw(query).ToListAsync();

                TempData["MessagemSucessoEdicao"] = "Curso Editado realizado com sucesso!!";

                return RedirectToAction(nameof(Index));

            }
            return View(curso);
        }
              
        public IActionResult Delete(int id)
        {
            return View(_context.Curso.FromSqlRaw("EXEC DetalheCurso " + id)
               .ToList().FirstOrDefault());
        }
               
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _context.Curso.FromSqlRaw("EXEC DeleteCurso " + id).ToListAsync();

            TempData["MessagemSucessoDelCurso"] = "Curso Removido com sucesso!!";

            _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

CRUD_Com_Procedures/Controllers/MatriculaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRUD_Com_Procedures.Models;


namespace CRUD_Com_Procedures.Controllers
{
    public class MatriculaController : Controller
    {
        private readonly Contexto _context;
        public MatriculaController(Contexto context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View (_context.Matricula.FromSqlRaw("EXEC DetalheMatriculaIndice ").ToList());
        }
        public IActionResult Details(int id)
        {            
            var matricula = _context.Matricula.FromSqlRaw("EXEC DetalheMatricula " + id).
                ToList().FirstOrDefault();

            return View(matricula);            
        }
        public IActionResult Create()
        {
            Matricula matriculas = new()
            {
                ContatosSelectListNome = new List<SelectListItem>(),
                ContatosSelectListCurso = new List<SelectListItem>()
            };

            foreach (var aluno in _context.Aluno)
            {      
                matriculas.ContatosSelectListNome.Add(new SelectListItem { 
                    Text = aluno.Nome, Value = aluno.Id.ToString()});
            }
            foreach (var curso in _context.Curso)
            {
                matriculas.ContatosSelectListCurso.Add(new SelectListItem { 
                    Text = curso.NomeCurso, Value = curso.Id.ToString()});
            }
            return View(matriculas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                var query = string.Format("EXEC CriarMatricula '{0}', '{1}';",
                    matricula.IdAluno, matricula.IdCurso);

                _context.Matricula.FromSqlRaw(query).ToListAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(matricula);
        }
        public IActionResult Edit()
        {
            Matricula matriculas = new()
            {
                ContatosSelectListNome = new List<SelectListItem>(),
                ContatosSelectListCurso = new List<SelectListItem>()
            };

            foreach (var aluno in _context.Aluno)
            {
                matriculas.ContatosSelectListNome.Add(new SelectListItem { 
                    Text = aluno.Nome, Value = aluno.Id.ToString() });
            }
            foreach (var curso in _context.Curso)
            {
                matriculas.ContatosSelectListCurso.Add(new SelectListItem { 
                    Text = curso.NomeCurso, Value = curso.Id.ToString() });
            }
            return View(matriculas);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Matricula matricula)
        {
            if (ModelState.IsValid)
            {
                var query = string.Format("EXEC EditarMatricula {0}, {1}, {2};",
                    id, matricula.IdAluno, matricula.IdCurso);

                _context.Matricula.FromSqlRaw(query).ToListAsync();

                return RedirectToAction(nameof(Index));
            }
            return View(matricula);
        }
        public IActionResult Delete(int id)
        {
            var matricula = _context.Matricula.FromSqlRaw("EXEC DetalheMatricula " + id).
                ToList().FirstOrDefault();

            return View(matricula);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _context.Matricula.FromSqlRaw("EXEC DeleteMatricula " + id).ToListAsync();
          
            _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

CRUD_Com_Procedures/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUD_Com_Procedures.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Aluno" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Curso" asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matricula" asp-action="Index">Matriculas</a>
                        </li>                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CRUD_Com_Procedures/Views/Shared/_LayoutDeslogado.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />    
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />   
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SINQIA EDUCATION</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
        
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>